### PR TITLE
OP4 + BShift ents, models and hud

### PR DESCRIPTION
**Pull request by RykahKnight**
Added OP4/BShift ents:
monster_otis
monster_otis_dead
monster_cleansuit_scientist
monster_cleansuit_scientist_dead
monster_sitting_cleansuit_scientist
item_helemt
item_armorvest

Also added OP4 weapons VMs + commity made versions of them with HL1 and BShift hands, HL1 MP5 on the OP4/BShift anims, OP4 hud and a fix for the normal scientist in BShift.

### CODE REVIEW

**Comment by Fograin** [comment]
Thank you for this commit, I'll check it later.
BTW: Additional .mdl models for OF weapons, are not required. They're loaded directly from mounted OF content.

**Comment by RykahKnight** [comment]
The reason why I included the of weapons with normal, bs and of versions is that the OF versions use the orignal OF hands, the BS versions have been reriged to the Blue Shift hands, and the non-postfixed ones have been reriged to HL1:LD hands.

I'm going to try to see if I can get a system in place for the hud stuff and weapon icons and such to check if it's OP4 or not to either use the non-scanlined (HL1/BShift) or the sanlined ones (OP4)

**Comment by RykahKnight** [comment]
I removed the OP4 Hud sprites, since they aren't needed here and I (currently) don't know of a way to make it choose between OP4 and Normal huds.
I also updated the code so it can be merged without problems.

**Comment by Fograin** [comment]
I'll check the code later when I'll start scripting BS/OF entities ;)

**Comment by RykahKnight** [comment]
I fixed the MP5 ammo sillyness.
And yeah, thanks c:

**Comment by RykahKnight** [comment]
Hey man, could you link me your steam account so we can co-lab on this easier?
If so, add me please c:
http://steamcommunity.com/id/ThatDamnedFoxWolf/

**Comment by Fograin** [comment]
I'm keeping my steam account friends list private for people I know in real life and for people I worked before for years :P Just commit changes/additions here. I'll check them when I'll have some free time.

**Comment by RykahKnight** [comment]
Alright, seems fair enough.

**Comment by RykahKnight** [comment]
Starting from fresh, a lot of what I was doing was outdated as hell.

**Pull request closed without merging**
